@echo off
echo Starting Unify Backend Services...

echo Setting up Python path...
set PYTHONPATH=%CD%\backend

echo Starting Entity Service...
start "Unify Entity Service" cmd /c "cd backend && uvicorn entity.entities:app --reload --port 8081"

echo Starting Auth Service...
start "Unify Auth Service" cmd /c "cd backend && uvicorn auth.auth:app --reload --port 8000"

echo Both services are starting...
echo Entity Service will be available at http://localhost:8081
echo Auth Service will be available at http://localhost:8000 