"""create_pages_table

Revision ID: 20250607_113848_8760_create_pages_table
Revises: 20250607_113848_3540_create_users_table
Create Date: 2025-06-07 11:38:48

"""
from alembic import op
import sqlalchemy as sa
import json

# revision identifiers, used by Alembic.
revision = '20250607_113848_8760_create_pages_table'
down_revision = '20250607_113848_3540_create_users_table'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pages',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('slug', sa.String(255), nullable=False, unique=True),
        sa.Column('entity_type', sa.String(255), nullable=False),
        sa.Column('layout', sa.JSON(), nullable=False),
        sa.Column('items_per_page', sa.Integer(), nullable=True, server_default="10")
    )
    
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    # ### end Alembic commands ###

